package com.gt.mall.bean;

import java.util.Date;

public class Card {

    /**
     * 积分卡
     */
    public static final int POINT_CARD    = 1;
    /**
     * 折扣卡
     */
    public static final int DISCOUNT_CARD = 2;
    /**
     * 储值卡
     */
    public static final int VALUE_CARD    = 3;

    public static final int TIME_CARD = 4; //时效卡

    public static final int FREQUENCY_CARD = 5;//次卡
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.mc_id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer mcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.cardNo
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private String cardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.ct_id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer ctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.gt_id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer gtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.public_Id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer publicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.receiveDate
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Date receivedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.source
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Byte source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.isbinding
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Byte isbinding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.money
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.frequency
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.gr_id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer grId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.expireDate
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Date expiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.ucId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer ucid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.nominateCode
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private String nominatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.systemcode
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private String systemcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.isChecked
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Byte ischecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.applyType
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Byte applytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.memberId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.changeCardType
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Byte changecardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.entityMemberId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer entitymemberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.cardStatus
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Byte cardstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.busId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer busid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.oldId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer oldid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.giveMoney
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Double givemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.shopId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_card.online
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    private Byte online;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.mc_id
     *
     * @return the value of t_member_card.mc_id
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getMcId() {
        return mcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.mc_id
     *
     * @param mcId the value for t_member_card.mc_id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setMcId( Integer mcId ) {
        this.mcId = mcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.cardNo
     *
     * @return the value of t_member_card.cardNo
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.cardNo
     *
     * @param cardno the value for t_member_card.cardNo
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setCardno( String cardno ) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.ct_id
     *
     * @return the value of t_member_card.ct_id
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getCtId() {
        return ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.ct_id
     *
     * @param ctId the value for t_member_card.ct_id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setCtId( Integer ctId ) {
        this.ctId = ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.gt_id
     *
     * @return the value of t_member_card.gt_id
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getGtId() {
        return gtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.gt_id
     *
     * @param gtId the value for t_member_card.gt_id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setGtId( Integer gtId ) {
        this.gtId = gtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.public_Id
     *
     * @return the value of t_member_card.public_Id
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getPublicId() {
        return publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.public_Id
     *
     * @param publicId the value for t_member_card.public_Id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setPublicId( Integer publicId ) {
        this.publicId = publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.receiveDate
     *
     * @return the value of t_member_card.receiveDate
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Date getReceivedate() {
        return receivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.receiveDate
     *
     * @param receivedate the value for t_member_card.receiveDate
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setReceivedate( Date receivedate ) {
        this.receivedate = receivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.source
     *
     * @return the value of t_member_card.source
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.source
     *
     * @param source the value for t_member_card.source
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setSource( Byte source ) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.isbinding
     *
     * @return the value of t_member_card.isbinding
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Byte getIsbinding() {
        return isbinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.isbinding
     *
     * @param isbinding the value for t_member_card.isbinding
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setIsbinding( Byte isbinding ) {
        this.isbinding = isbinding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.money
     *
     * @return the value of t_member_card.money
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.money
     *
     * @param money the value for t_member_card.money
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setMoney( Double money ) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.frequency
     *
     * @return the value of t_member_card.frequency
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.frequency
     *
     * @param frequency the value for t_member_card.frequency
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setFrequency( Integer frequency ) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.gr_id
     *
     * @return the value of t_member_card.gr_id
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getGrId() {
        return grId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.gr_id
     *
     * @param grId the value for t_member_card.gr_id
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setGrId( Integer grId ) {
        this.grId = grId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.expireDate
     *
     * @return the value of t_member_card.expireDate
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Date getExpiredate() {
        return expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.expireDate
     *
     * @param expiredate the value for t_member_card.expireDate
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setExpiredate( Date expiredate ) {
        this.expiredate = expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.ucId
     *
     * @return the value of t_member_card.ucId
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getUcid() {
        return ucid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.ucId
     *
     * @param ucid the value for t_member_card.ucId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setUcid( Integer ucid ) {
        this.ucid = ucid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.nominateCode
     *
     * @return the value of t_member_card.nominateCode
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public String getNominatecode() {
        return nominatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.nominateCode
     *
     * @param nominatecode the value for t_member_card.nominateCode
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setNominatecode( String nominatecode ) {
        this.nominatecode = nominatecode == null ? null : nominatecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.systemcode
     *
     * @return the value of t_member_card.systemcode
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public String getSystemcode() {
        return systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.systemcode
     *
     * @param systemcode the value for t_member_card.systemcode
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setSystemcode( String systemcode ) {
        this.systemcode = systemcode == null ? null : systemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.isChecked
     *
     * @return the value of t_member_card.isChecked
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Byte getIschecked() {
        return ischecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.isChecked
     *
     * @param ischecked the value for t_member_card.isChecked
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setIschecked( Byte ischecked ) {
        this.ischecked = ischecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.applyType
     *
     * @return the value of t_member_card.applyType
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Byte getApplytype() {
        return applytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.applyType
     *
     * @param applytype the value for t_member_card.applyType
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setApplytype( Byte applytype ) {
        this.applytype = applytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.memberId
     *
     * @return the value of t_member_card.memberId
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.memberId
     *
     * @param memberid the value for t_member_card.memberId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setMemberid( Integer memberid ) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.changeCardType
     *
     * @return the value of t_member_card.changeCardType
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Byte getChangecardtype() {
        return changecardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.changeCardType
     *
     * @param changecardtype the value for t_member_card.changeCardType
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setChangecardtype( Byte changecardtype ) {
        this.changecardtype = changecardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.entityMemberId
     *
     * @return the value of t_member_card.entityMemberId
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getEntitymemberid() {
        return entitymemberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.entityMemberId
     *
     * @param entitymemberid the value for t_member_card.entityMemberId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setEntitymemberid( Integer entitymemberid ) {
        this.entitymemberid = entitymemberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.cardStatus
     *
     * @return the value of t_member_card.cardStatus
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Byte getCardstatus() {
        return cardstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.cardStatus
     *
     * @param cardstatus the value for t_member_card.cardStatus
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setCardstatus( Byte cardstatus ) {
        this.cardstatus = cardstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.busId
     *
     * @return the value of t_member_card.busId
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getBusid() {
        return busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.busId
     *
     * @param busid the value for t_member_card.busId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setBusid( Integer busid ) {
        this.busid = busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.oldId
     *
     * @return the value of t_member_card.oldId
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getOldid() {
        return oldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.oldId
     *
     * @param oldid the value for t_member_card.oldId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setOldid( Integer oldid ) {
        this.oldid = oldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.giveMoney
     *
     * @return the value of t_member_card.giveMoney
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Double getGivemoney() {
        return givemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.giveMoney
     *
     * @param givemoney the value for t_member_card.giveMoney
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setGivemoney( Double givemoney ) {
        this.givemoney = givemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.shopId
     *
     * @return the value of t_member_card.shopId
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.shopId
     *
     * @param shopid the value for t_member_card.shopId
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setShopid( Integer shopid ) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_card.online
     *
     * @return the value of t_member_card.online
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public Byte getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_card.online
     *
     * @param online the value for t_member_card.online
     *
     * @mbggenerated Thu May 11 15:47:22 CST 2017
     */
    public void setOnline( Byte online ) {
        this.online = online;
    }
}
