package com.gt.mall.bean;

public class MemberAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eat_member_address.id
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eat_member_address.mem_name
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    private String memName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eat_member_address.mem_phone
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    private String memPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eat_member_address.mem_address
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    private String memAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eat_member_address.mem_longitude
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    private String memLongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eat_member_address.mem_latitude
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    private String memLatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eat_member_address.df_member_id
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    private Integer dfMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eat_member_address.mem_default
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    private Integer memDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eat_member_address.mem_house_member
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    private String memHouseMember;
    
    private String memZipCode;
    
    private Integer memProvince;
    
    private Integer memCity;
    
    private Integer memArea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eat_member_address.id
     *
     * @return the value of t_eat_member_address.id
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eat_member_address.id
     *
     * @param id the value for t_eat_member_address.id
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eat_member_address.mem_name
     *
     * @return the value of t_eat_member_address.mem_name
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public String getMemName() {
        return memName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eat_member_address.mem_name
     *
     * @param memName the value for t_eat_member_address.mem_name
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public void setMemName(String memName) {
        this.memName = memName == null ? null : memName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eat_member_address.mem_phone
     *
     * @return the value of t_eat_member_address.mem_phone
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public String getMemPhone() {
        return memPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eat_member_address.mem_phone
     *
     * @param memPhone the value for t_eat_member_address.mem_phone
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public void setMemPhone(String memPhone) {
        this.memPhone = memPhone == null ? null : memPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eat_member_address.mem_address
     *
     * @return the value of t_eat_member_address.mem_address
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public String getMemAddress() {
        return memAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eat_member_address.mem_address
     *
     * @param memAddress the value for t_eat_member_address.mem_address
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public void setMemAddress(String memAddress) {
        this.memAddress = memAddress == null ? null : memAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eat_member_address.mem_longitude
     *
     * @return the value of t_eat_member_address.mem_longitude
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public String getMemLongitude() {
        return memLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eat_member_address.mem_longitude
     *
     * @param memLongitude the value for t_eat_member_address.mem_longitude
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public void setMemLongitude(String memLongitude) {
        this.memLongitude = memLongitude == null ? null : memLongitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eat_member_address.mem_latitude
     *
     * @return the value of t_eat_member_address.mem_latitude
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public String getMemLatitude() {
        return memLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eat_member_address.mem_latitude
     *
     * @param memLatitude the value for t_eat_member_address.mem_latitude
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public void setMemLatitude(String memLatitude) {
        this.memLatitude = memLatitude == null ? null : memLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eat_member_address.df_member_id
     *
     * @return the value of t_eat_member_address.df_member_id
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public Integer getDfMemberId() {
        return dfMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eat_member_address.df_member_id
     *
     * @param dfMemberId the value for t_eat_member_address.df_member_id
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public void setDfMemberId(Integer dfMemberId) {
        this.dfMemberId = dfMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eat_member_address.mem_default
     *
     * @return the value of t_eat_member_address.mem_default
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public Integer getMemDefault() {
        return memDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eat_member_address.mem_default
     *
     * @param memDefault the value for t_eat_member_address.mem_default
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public void setMemDefault(Integer memDefault) {
        this.memDefault = memDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eat_member_address.mem_house_member
     *
     * @return the value of t_eat_member_address.mem_house_member
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public String getMemHouseMember() {
        return memHouseMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eat_member_address.mem_house_member
     *
     * @param memHouseMember the value for t_eat_member_address.mem_house_member
     *
     * @mbggenerated Mon Mar 14 14:53:37 CST 2016
     */
    public void setMemHouseMember(String memHouseMember) {
        this.memHouseMember = memHouseMember == null ? null : memHouseMember.trim();
    }

	public String getMemZipCode() {
		return memZipCode;
	}

	public void setMemZipCode(String memZipCode) {
		this.memZipCode = memZipCode;
	}

	public Integer getMemProvince() {
		return memProvince;
	}

	public void setMemProvince(Integer memProvince) {
		this.memProvince = memProvince;
	}

	public Integer getMemCity() {
		return memCity;
	}

	public void setMemCity(Integer memCity) {
		this.memCity = memCity;
	}

	public Integer getMemArea() {
		return memArea;
	}

	public void setMemArea(Integer memArea) {
		this.memArea = memArea;
	}
    
    
}