package com.gt.mall.bean;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;

@Getter
@Setter
public class Member implements Serializable {
    /**
     *
     */
    private static final long serialVersionUID = 2520956702713776574L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.df_member_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer dfMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.public_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer publicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.fans_currency
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Double fansCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.flow
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer flow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.integral
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.level
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.openid
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.phone
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.sex
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.province
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.city
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.country
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.headimgurl
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.operate_type
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.mc_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer mcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.totalMoney
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Double totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.totalIntegral
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer totalintegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.address
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.email
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.cardId
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.cardImgback
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String cardimgback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.cardImg
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String cardimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.birth
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.currencyDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date currencydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.flowDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date flowdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.integralDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date integraldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.shareCount
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer sharecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.shareDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date sharedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.remark
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.cardChecked
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Byte cardchecked;

    private Byte isbuy;

    private boolean isPass = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.name
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.nickname
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String nickname;

    private String scenceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.busId
     *
     * @mbggenerated Tue Dec 13 15:57:54 CST 2016
     */
    private Integer busid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.pwd
     *
     * @mbggenerated Tue Dec 13 15:57:54 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.loginMode
     *
     * @mbggenerated Tue Dec 13 15:57:54 CST 2016
     */
    private Byte loginmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.oldId
     *
     * @mbggenerated Tue Dec 13 15:57:54 CST 2016
     */
    private String oldid;

    private String openid2;
    private Byte   issubscribe;
    private Date   subscribedate;


}