package com.gt.mall.bean;

public class PublicParameterSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.id
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.integralRatio
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Double integralratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.changeMoney
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Double changemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.startMoney
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Double startmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.publicId
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Integer publicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.startType
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Byte starttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.findImage
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private String findimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.isOpenCard
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Byte isopencard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.busId
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Integer busid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.loginImage
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private String loginimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.isclearJifen
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Byte isclearjifen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.month
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.memberView
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Byte memberview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.youhuiButton
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private String youhuibutton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.youhuiText
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private String youhuitext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.buttonType
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private Byte buttontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_public_parameterset.buttonUrl
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    private String buttonurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.id
     *
     * @return the value of t_public_parameterset.id
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.id
     *
     * @param id the value for t_public_parameterset.id
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.integralRatio
     *
     * @return the value of t_public_parameterset.integralRatio
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Double getIntegralratio() {
        return integralratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.integralRatio
     *
     * @param integralratio the value for t_public_parameterset.integralRatio
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setIntegralratio(Double integralratio) {
        this.integralratio = integralratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.changeMoney
     *
     * @return the value of t_public_parameterset.changeMoney
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Double getChangemoney() {
        return changemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.changeMoney
     *
     * @param changemoney the value for t_public_parameterset.changeMoney
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setChangemoney(Double changemoney) {
        this.changemoney = changemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.startMoney
     *
     * @return the value of t_public_parameterset.startMoney
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Double getStartmoney() {
        return startmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.startMoney
     *
     * @param startmoney the value for t_public_parameterset.startMoney
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setStartmoney(Double startmoney) {
        this.startmoney = startmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.publicId
     *
     * @return the value of t_public_parameterset.publicId
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Integer getPublicid() {
        return publicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.publicId
     *
     * @param publicid the value for t_public_parameterset.publicId
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setPublicid(Integer publicid) {
        this.publicid = publicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.startType
     *
     * @return the value of t_public_parameterset.startType
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Byte getStarttype() {
        return starttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.startType
     *
     * @param starttype the value for t_public_parameterset.startType
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setStarttype(Byte starttype) {
        this.starttype = starttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.findImage
     *
     * @return the value of t_public_parameterset.findImage
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public String getFindimage() {
        return findimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.findImage
     *
     * @param findimage the value for t_public_parameterset.findImage
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setFindimage(String findimage) {
        this.findimage = findimage == null ? null : findimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.isOpenCard
     *
     * @return the value of t_public_parameterset.isOpenCard
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Byte getIsopencard() {
        return isopencard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.isOpenCard
     *
     * @param isopencard the value for t_public_parameterset.isOpenCard
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setIsopencard(Byte isopencard) {
        this.isopencard = isopencard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.busId
     *
     * @return the value of t_public_parameterset.busId
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Integer getBusid() {
        return busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.busId
     *
     * @param busid the value for t_public_parameterset.busId
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setBusid(Integer busid) {
        this.busid = busid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.loginImage
     *
     * @return the value of t_public_parameterset.loginImage
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public String getLoginimage() {
        return loginimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.loginImage
     *
     * @param loginimage the value for t_public_parameterset.loginImage
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setLoginimage(String loginimage) {
        this.loginimage = loginimage == null ? null : loginimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.isclearJifen
     *
     * @return the value of t_public_parameterset.isclearJifen
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Byte getIsclearjifen() {
        return isclearjifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.isclearJifen
     *
     * @param isclearjifen the value for t_public_parameterset.isclearJifen
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setIsclearjifen(Byte isclearjifen) {
        this.isclearjifen = isclearjifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.month
     *
     * @return the value of t_public_parameterset.month
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.month
     *
     * @param month the value for t_public_parameterset.month
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.memberView
     *
     * @return the value of t_public_parameterset.memberView
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Byte getMemberview() {
        return memberview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.memberView
     *
     * @param memberview the value for t_public_parameterset.memberView
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setMemberview(Byte memberview) {
        this.memberview = memberview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.youhuiButton
     *
     * @return the value of t_public_parameterset.youhuiButton
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public String getYouhuibutton() {
        return youhuibutton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.youhuiButton
     *
     * @param youhuibutton the value for t_public_parameterset.youhuiButton
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setYouhuibutton(String youhuibutton) {
        this.youhuibutton = youhuibutton == null ? null : youhuibutton.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.youhuiText
     *
     * @return the value of t_public_parameterset.youhuiText
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public String getYouhuitext() {
        return youhuitext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.youhuiText
     *
     * @param youhuitext the value for t_public_parameterset.youhuiText
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setYouhuitext(String youhuitext) {
        this.youhuitext = youhuitext == null ? null : youhuitext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.buttonType
     *
     * @return the value of t_public_parameterset.buttonType
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public Byte getButtontype() {
        return buttontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.buttonType
     *
     * @param buttontype the value for t_public_parameterset.buttonType
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setButtontype(Byte buttontype) {
        this.buttontype = buttontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_public_parameterset.buttonUrl
     *
     * @return the value of t_public_parameterset.buttonUrl
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public String getButtonurl() {
        return buttonurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_public_parameterset.buttonUrl
     *
     * @param buttonurl the value for t_public_parameterset.buttonUrl
     *
     * @mbggenerated Thu May 25 16:06:43 CST 2017
     */
    public void setButtonurl(String buttonurl) {
        this.buttonurl = buttonurl == null ? null : buttonurl.trim();
    }
}