package com.gt.mall.bean;

import org.apache.commons.lang.StringUtils;

import java.util.Date;

public class UserConsume {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.id
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.public_id
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer publicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.busUserId
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer bususerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.memberId
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.storeId
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.isParent
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte isparent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.freightMoney
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Double freightmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.mcId
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer mcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.ctId
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer ctid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.gt_id
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer gtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.recordType
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte recordtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.ucType
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte uctype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.totalMoney
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Double totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.integral
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.fenbi
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Double fenbi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.uccount
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer uccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.discount
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.discountMoney
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Double discountmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.orderId
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.ucTable
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private String uctable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.giveIntegral
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer giveintegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.giveFlow
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer giveflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.giveFenbi
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Double givefenbi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.createDate
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.paymentType
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte paymenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.dvId
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer dvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.disCountdepict
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private String discountdepict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.balance
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.payStatus
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.giveGift
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private String givegift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.giftCount
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer giftcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.orderCode
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private String ordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.moduleType
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte moduletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.offlinePayType
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte offlinepaytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.cardType
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.flowState
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte flowstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.dataSource
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Byte datasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.moduleOrderType
     *
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    private Integer moduleordertype;


    private Byte isend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.id
     *
     * @return the value of t_wx_user_consume.id
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.id
     *
     * @param id the value for t_wx_user_consume.id
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.public_id
     *
     * @return the value of t_wx_user_consume.public_id
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getPublicId() {
        return publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.public_id
     *
     * @param publicId the value for t_wx_user_consume.public_id
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setPublicId(Integer publicId) {
        this.publicId = publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.busUserId
     *
     * @return the value of t_wx_user_consume.busUserId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getBususerid() {
        return bususerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.busUserId
     *
     * @param bususerid the value for t_wx_user_consume.busUserId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setBususerid(Integer bususerid) {
        this.bususerid = bususerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.memberId
     *
     * @return the value of t_wx_user_consume.memberId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.memberId
     *
     * @param memberid the value for t_wx_user_consume.memberId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.storeId
     *
     * @return the value of t_wx_user_consume.storeId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.storeId
     *
     * @param storeid the value for t_wx_user_consume.storeId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.isParent
     *
     * @return the value of t_wx_user_consume.isParent
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getIsparent() {
        return isparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.isParent
     *
     * @param isparent the value for t_wx_user_consume.isParent
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setIsparent(Byte isparent) {
        this.isparent = isparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.freightMoney
     *
     * @return the value of t_wx_user_consume.freightMoney
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Double getFreightmoney() {
        return freightmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.freightMoney
     *
     * @param freightmoney the value for t_wx_user_consume.freightMoney
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setFreightmoney(Double freightmoney) {
        this.freightmoney = freightmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.mcId
     *
     * @return the value of t_wx_user_consume.mcId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getMcid() {
        return mcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.mcId
     *
     * @param mcid the value for t_wx_user_consume.mcId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setMcid(Integer mcid) {
        this.mcid = mcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.ctId
     *
     * @return the value of t_wx_user_consume.ctId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getCtid() {
        return ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.ctId
     *
     * @param ctid the value for t_wx_user_consume.ctId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setCtid(Integer ctid) {
        this.ctid = ctid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.gt_id
     *
     * @return the value of t_wx_user_consume.gt_id
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getGtId() {
        return gtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.gt_id
     *
     * @param gtId the value for t_wx_user_consume.gt_id
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setGtId(Integer gtId) {
        this.gtId = gtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.recordType
     *
     * @return the value of t_wx_user_consume.recordType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getRecordtype() {
        return recordtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.recordType
     *
     * @param recordtype the value for t_wx_user_consume.recordType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setRecordtype(Byte recordtype) {
        this.recordtype = recordtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.ucType
     *
     * @return the value of t_wx_user_consume.ucType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getUctype() {
        return uctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.ucType
     *
     * @param uctype the value for t_wx_user_consume.ucType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setUctype(Byte uctype) {
        this.uctype = uctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.totalMoney
     *
     * @return the value of t_wx_user_consume.totalMoney
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Double getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.totalMoney
     *
     * @param totalmoney the value for t_wx_user_consume.totalMoney
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setTotalmoney(Double totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.integral
     *
     * @return the value of t_wx_user_consume.integral
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.integral
     *
     * @param integral the value for t_wx_user_consume.integral
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.fenbi
     *
     * @return the value of t_wx_user_consume.fenbi
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Double getFenbi() {
        return fenbi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.fenbi
     *
     * @param fenbi the value for t_wx_user_consume.fenbi
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setFenbi(Object fenbi) {
        if (StringUtils.isNotEmpty(fenbi.toString())) {
            this.fenbi = new Double(fenbi.toString());
        } else {
            this.fenbi = 0.0;
        }

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.uccount
     *
     * @return the value of t_wx_user_consume.uccount
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getUccount() {
        return uccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.uccount
     *
     * @param uccount the value for t_wx_user_consume.uccount
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setUccount(Integer uccount) {
        this.uccount = uccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.discount
     *
     * @return the value of t_wx_user_consume.discount
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.discount
     *
     * @param discount the value for t_wx_user_consume.discount
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.discountMoney
     *
     * @return the value of t_wx_user_consume.discountMoney
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Double getDiscountmoney() {
        return discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.discountMoney
     *
     * @param discountmoney the value for t_wx_user_consume.discountMoney
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setDiscountmoney(Double discountmoney) {
        this.discountmoney = discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.orderId
     *
     * @return the value of t_wx_user_consume.orderId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.orderId
     *
     * @param orderid the value for t_wx_user_consume.orderId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.ucTable
     *
     * @return the value of t_wx_user_consume.ucTable
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public String getUctable() {
        return uctable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.ucTable
     *
     * @param uctable the value for t_wx_user_consume.ucTable
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setUctable(String uctable) {
        this.uctable = uctable == null ? null : uctable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.giveIntegral
     *
     * @return the value of t_wx_user_consume.giveIntegral
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getGiveintegral() {
        return giveintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.giveIntegral
     *
     * @param giveintegral the value for t_wx_user_consume.giveIntegral
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setGiveintegral(Integer giveintegral) {
        this.giveintegral = giveintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.giveFlow
     *
     * @return the value of t_wx_user_consume.giveFlow
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getGiveflow() {
        return giveflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.giveFlow
     *
     * @param giveflow the value for t_wx_user_consume.giveFlow
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setGiveflow(Integer giveflow) {
        this.giveflow = giveflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.giveFenbi
     *
     * @return the value of t_wx_user_consume.giveFenbi
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Double getGivefenbi() {
        return givefenbi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.giveFenbi
     *
     * @param givefenbi the value for t_wx_user_consume.giveFenbi
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setGivefenbi(Object givefenbi) {
        if (StringUtils.isNotEmpty(givefenbi.toString())) {
            this.givefenbi = new Double(givefenbi.toString());
        } else {
            this.givefenbi = 0.0;
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.createDate
     *
     * @return the value of t_wx_user_consume.createDate
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.createDate
     *
     * @param createdate the value for t_wx_user_consume.createDate
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.paymentType
     *
     * @return the value of t_wx_user_consume.paymentType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getPaymenttype() {
        return paymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.paymentType
     *
     * @param paymenttype the value for t_wx_user_consume.paymentType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setPaymenttype(Byte paymenttype) {
        this.paymenttype = paymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.dvId
     *
     * @return the value of t_wx_user_consume.dvId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getDvid() {
        return dvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.dvId
     *
     * @param dvid the value for t_wx_user_consume.dvId
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setDvid(Integer dvid) {
        this.dvid = dvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.disCountdepict
     *
     * @return the value of t_wx_user_consume.disCountdepict
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public String getDiscountdepict() {
        return discountdepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.disCountdepict
     *
     * @param discountdepict the value for t_wx_user_consume.disCountdepict
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setDiscountdepict(String discountdepict) {
        this.discountdepict = discountdepict == null ? null : discountdepict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.balance
     *
     * @return the value of t_wx_user_consume.balance
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.balance
     *
     * @param balance the value for t_wx_user_consume.balance
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.payStatus
     *
     * @return the value of t_wx_user_consume.payStatus
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.payStatus
     *
     * @param paystatus the value for t_wx_user_consume.payStatus
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setPaystatus(Byte paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.giveGift
     *
     * @return the value of t_wx_user_consume.giveGift
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public String getGivegift() {
        return givegift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.giveGift
     *
     * @param givegift the value for t_wx_user_consume.giveGift
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setGivegift(String givegift) {
        this.givegift = givegift == null ? null : givegift.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.giftCount
     *
     * @return the value of t_wx_user_consume.giftCount
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getGiftcount() {
        return giftcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.giftCount
     *
     * @param giftcount the value for t_wx_user_consume.giftCount
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setGiftcount(Integer giftcount) {
        this.giftcount = giftcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.orderCode
     *
     * @return the value of t_wx_user_consume.orderCode
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.orderCode
     *
     * @param ordercode the value for t_wx_user_consume.orderCode
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.moduleType
     *
     * @return the value of t_wx_user_consume.moduleType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getModuletype() {
        return moduletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.moduleType
     *
     * @param moduletype the value for t_wx_user_consume.moduleType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setModuletype(Byte moduletype) {
        this.moduletype = moduletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.offlinePayType
     *
     * @return the value of t_wx_user_consume.offlinePayType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getOfflinepaytype() {
        return offlinepaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.offlinePayType
     *
     * @param offlinepaytype the value for t_wx_user_consume.offlinePayType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setOfflinepaytype(Byte offlinepaytype) {
        this.offlinepaytype = offlinepaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.cardType
     *
     * @return the value of t_wx_user_consume.cardType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.cardType
     *
     * @param cardtype the value for t_wx_user_consume.cardType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setCardtype(Byte cardtype) {
        this.cardtype = cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.flowState
     *
     * @return the value of t_wx_user_consume.flowState
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getFlowstate() {
        return flowstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.flowState
     *
     * @param flowstate the value for t_wx_user_consume.flowState
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setFlowstate(Byte flowstate) {
        this.flowstate = flowstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.dataSource
     *
     * @return the value of t_wx_user_consume.dataSource
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Byte getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.dataSource
     *
     * @param datasource the value for t_wx_user_consume.dataSource
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setDatasource(Byte datasource) {
        this.datasource = datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.moduleOrderType
     *
     * @return the value of t_wx_user_consume.moduleOrderType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public Integer getModuleordertype() {
        return moduleordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.moduleOrderType
     *
     * @param moduleordertype the value for t_wx_user_consume.moduleOrderType
     * @mbggenerated Fri May 12 11:53:59 CST 2017
     */
    public void setModuleordertype(Integer moduleordertype) {
        this.moduleordertype = moduleordertype;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.isend
     *
     * @return the value of t_wx_user_consume.isend
     * @mbggenerated Fri May 12 17:50:15 CST 2017
     */
    public Byte getIsend() {
        return isend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.isend
     *
     * @param isend the value for t_wx_user_consume.isend
     * @mbggenerated Fri May 12 17:50:15 CST 2017
     */
    public void setIsend(Byte isend) {
        this.isend = isend;
    }


    private Byte ischongzhi;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.ischongzhi
     *
     * @return the value of t_wx_user_consume.ischongzhi
     * @mbggenerated Mon May 15 14:49:54 CST 2017
     */
    public Byte getIschongzhi() {
        return ischongzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.ischongzhi
     *
     * @param ischongzhi the value for t_wx_user_consume.ischongzhi
     * @mbggenerated Mon May 15 14:49:54 CST 2017
     */
    public void setIschongzhi(Byte ischongzhi) {
        this.ischongzhi = ischongzhi;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_user_consume.isendDate
     *
     * @mbggenerated Mon May 15 15:36:40 CST 2017
     */
    private Date isenddate;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_user_consume.isendDate
     *
     * @return the value of t_wx_user_consume.isendDate
     * @mbggenerated Mon May 15 15:36:40 CST 2017
     */
    public Date getIsenddate() {
        return isenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_user_consume.isendDate
     *
     * @param isenddate the value for t_wx_user_consume.isendDate
     * @mbggenerated Mon May 15 15:36:40 CST 2017
     */
    public void setIsenddate(Date isenddate) {
        this.isenddate = isenddate;
    }
}