package com.gt.mall.bean;

import java.util.List;

public class WxApplet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_applet.id
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_applet.bus_id
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    private Integer busId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_applet.appid
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_applet.appsecret
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    private String appsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_applet.mch_id
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_applet.api_key
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    private String apiKey;
    
    
    private String nickName;
    
    private String headImg;
    
    private String qrcodeUrl;
    
    private String certificateUrl;
    
    private Integer industryCode;
    
    private String industryCodeDesc="未知";
    
    private Integer serviceTypeInfo;
    
    private Integer verifyTypeInfo;
    
    private String userName;
    
    private String signature;
    
    private String principalName;
    
    private String businessInfo;
    
    private Integer visitStatus;
    
    private String categories;
    
    private String network;
    
    private String authorizerRefreshToken;
    
    
    private Integer status;
    
    
    private String pageQrcodeUrl;

    
    private String experienceQrUrl;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_applet.id
     *
     * @return the value of t_wx_applet.id
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_applet.id
     *
     * @param id the value for t_wx_applet.id
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_applet.bus_id
     *
     * @return the value of t_wx_applet.bus_id
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public Integer getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_applet.bus_id
     *
     * @param busId the value for t_wx_applet.bus_id
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_applet.appid
     *
     * @return the value of t_wx_applet.appid
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_applet.appid
     *
     * @param appid the value for t_wx_applet.appid
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_applet.appsecret
     *
     * @return the value of t_wx_applet.appsecret
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_applet.appsecret
     *
     * @param appsecret the value for t_wx_applet.appsecret
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_applet.mch_id
     *
     * @return the value of t_wx_applet.mch_id
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_applet.mch_id
     *
     * @param mchId the value for t_wx_applet.mch_id
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_applet.api_key
     *
     * @return the value of t_wx_applet.api_key
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_applet.api_key
     *
     * @param apiKey the value for t_wx_applet.api_key
     *
     * @mbggenerated Tue Feb 21 10:38:18 CST 2017
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey == null ? null : apiKey.trim();
    }


	public String getHeadImg() {
		return headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	public String getQrcodeUrl() {
		return qrcodeUrl;
	}

	public void setQrcodeUrl(String qrcodeUrl) {
		this.qrcodeUrl = qrcodeUrl;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getCertificateUrl() {
		return certificateUrl;
	}

	public void setCertificateUrl(String certificateUrl) {
		this.certificateUrl = certificateUrl;
	}

	public Integer getIndustryCode() {
		return industryCode;
	}

	public void setIndustryCode(Integer industryCode) {
		this.industryCode = industryCode;
	}

	public String getIndustryCodeDesc() {
		return industryCodeDesc;
	}

	public void setIndustryCodeDesc(String industryCodeDesc) {
		this.industryCodeDesc = industryCodeDesc;
	}

	public Integer getServiceTypeInfo() {
		return serviceTypeInfo;
	}

	public void setServiceTypeInfo(Integer serviceTypeInfo) {
		this.serviceTypeInfo = serviceTypeInfo;
	}

	public Integer getVerifyTypeInfo() {
		return verifyTypeInfo;
	}

	public void setVerifyTypeInfo(Integer verifyTypeInfo) {
		this.verifyTypeInfo = verifyTypeInfo;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getPrincipalName() {
		return principalName;
	}

	public void setPrincipalName(String principalName) {
		this.principalName = principalName;
	}

	public String getBusinessInfo() {
		return businessInfo;
	}

	public void setBusinessInfo(String businessInfo) {
		this.businessInfo = businessInfo;
	}

	public Integer getVisitStatus() {
		return visitStatus;
	}

	public void setVisitStatus(Integer visitStatus) {
		this.visitStatus = visitStatus;
	}

	public String getCategories() {
		return categories;
	}

	public void setCategories(String categories) {
		this.categories = categories;
	}

	public String getNetwork() {
		return network;
	}

	public void setNetwork(String network) {
		this.network = network;
	}

	public String getAuthorizerRefreshToken() {
		return authorizerRefreshToken;
	}

	public void setAuthorizerRefreshToken(String authorizerRefreshToken) {
		this.authorizerRefreshToken = authorizerRefreshToken;
	}



	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getPageQrcodeUrl() {
		return pageQrcodeUrl;
	}

	public String getExperienceQrUrl() {
		return experienceQrUrl;
	}

	public void setExperienceQrUrl(String experienceQrUrl) {
		this.experienceQrUrl = experienceQrUrl;
	}

	public void setPageQrcodeUrl(String pageQrcodeUrl) {
		this.pageQrcodeUrl = pageQrcodeUrl;
	}

}