package com.gt.mall.bean;

import java.util.Date;

public class WxPayOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.out_trade_no
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.transaction_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.fee_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.total_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Double totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.refund_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Double refundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.spbill_create_ip
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String spbillCreateIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.time_start
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Date timeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.time_expire
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Date timeExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.trade_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.product_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.prepay_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String prepayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.code_url
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String codeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.err_code_des
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String errCodeDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.openid
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.trade_state
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String tradeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.bank_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String bankType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.cash_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Double cashFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.cash_fee_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String cashFeeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.coupon_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Double couponFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.coupon_count
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Integer couponCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.time_end
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Date timeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.out_refund_no
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String outRefundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.refund_fee_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String refundFeeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.op_user_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String opUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.refund_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String refundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.refund_channel
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String refundChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.cash_refund_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Double cashRefundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.coupon_refund_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Double couponRefundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.coupon_refund_count
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private Integer couponRefundCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.coupon_refund_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String couponRefundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.refund_status
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_pay_order.refund_recv_accout
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    private String refundRecvAccout;
    
    private Integer model;
    
    private Integer pay_type;
    
    private Integer bus_id;
    
    
    private String businessName;
    
    
    private Integer paySource;
    
    private String submitNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.id
     *
     * @return the value of t_wx_pay_order.id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.id
     *
     * @param id the value for t_wx_pay_order.id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.out_trade_no
     *
     * @return the value of t_wx_pay_order.out_trade_no
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.out_trade_no
     *
     * @param outTradeNo the value for t_wx_pay_order.out_trade_no
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.transaction_id
     *
     * @return the value of t_wx_pay_order.transaction_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.transaction_id
     *
     * @param transactionId the value for t_wx_pay_order.transaction_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.fee_type
     *
     * @return the value of t_wx_pay_order.fee_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.fee_type
     *
     * @param feeType the value for t_wx_pay_order.fee_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType == null ? null : feeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.total_fee
     *
     * @return the value of t_wx_pay_order.total_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.total_fee
     *
     * @param totalFee the value for t_wx_pay_order.total_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.refund_fee
     *
     * @return the value of t_wx_pay_order.refund_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Double getRefundFee() {
        return refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.refund_fee
     *
     * @param refundFee the value for t_wx_pay_order.refund_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setRefundFee(Double refundFee) {
        this.refundFee = refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.spbill_create_ip
     *
     * @return the value of t_wx_pay_order.spbill_create_ip
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getSpbillCreateIp() {
        return spbillCreateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.spbill_create_ip
     *
     * @param spbillCreateIp the value for t_wx_pay_order.spbill_create_ip
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setSpbillCreateIp(String spbillCreateIp) {
        this.spbillCreateIp = spbillCreateIp == null ? null : spbillCreateIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.time_start
     *
     * @return the value of t_wx_pay_order.time_start
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Date getTimeStart() {
        return timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.time_start
     *
     * @param timeStart the value for t_wx_pay_order.time_start
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.time_expire
     *
     * @return the value of t_wx_pay_order.time_expire
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Date getTimeExpire() {
        return timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.time_expire
     *
     * @param timeExpire the value for t_wx_pay_order.time_expire
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setTimeExpire(Date timeExpire) {
        this.timeExpire = timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.trade_type
     *
     * @return the value of t_wx_pay_order.trade_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.trade_type
     *
     * @param tradeType the value for t_wx_pay_order.trade_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.product_id
     *
     * @return the value of t_wx_pay_order.product_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.product_id
     *
     * @param productId the value for t_wx_pay_order.product_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.prepay_id
     *
     * @return the value of t_wx_pay_order.prepay_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.prepay_id
     *
     * @param prepayId the value for t_wx_pay_order.prepay_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.code_url
     *
     * @return the value of t_wx_pay_order.code_url
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getCodeUrl() {
        return codeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.code_url
     *
     * @param codeUrl the value for t_wx_pay_order.code_url
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setCodeUrl(String codeUrl) {
        this.codeUrl = codeUrl == null ? null : codeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.err_code_des
     *
     * @return the value of t_wx_pay_order.err_code_des
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getErrCodeDes() {
        return errCodeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.err_code_des
     *
     * @param errCodeDes the value for t_wx_pay_order.err_code_des
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setErrCodeDes(String errCodeDes) {
        this.errCodeDes = errCodeDes == null ? null : errCodeDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.openid
     *
     * @return the value of t_wx_pay_order.openid
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.openid
     *
     * @param openid the value for t_wx_pay_order.openid
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.trade_state
     *
     * @return the value of t_wx_pay_order.trade_state
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getTradeState() {
        return tradeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.trade_state
     *
     * @param tradeState the value for t_wx_pay_order.trade_state
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setTradeState(String tradeState) {
        this.tradeState = tradeState == null ? null : tradeState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.bank_type
     *
     * @return the value of t_wx_pay_order.bank_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.bank_type
     *
     * @param bankType the value for t_wx_pay_order.bank_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.cash_fee
     *
     * @return the value of t_wx_pay_order.cash_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Double getCashFee() {
        return cashFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.cash_fee
     *
     * @param cashFee the value for t_wx_pay_order.cash_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setCashFee(Double cashFee) {
        this.cashFee = cashFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.cash_fee_type
     *
     * @return the value of t_wx_pay_order.cash_fee_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getCashFeeType() {
        return cashFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.cash_fee_type
     *
     * @param cashFeeType the value for t_wx_pay_order.cash_fee_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setCashFeeType(String cashFeeType) {
        this.cashFeeType = cashFeeType == null ? null : cashFeeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.coupon_fee
     *
     * @return the value of t_wx_pay_order.coupon_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Double getCouponFee() {
        return couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.coupon_fee
     *
     * @param couponFee the value for t_wx_pay_order.coupon_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setCouponFee(Double couponFee) {
        this.couponFee = couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.coupon_count
     *
     * @return the value of t_wx_pay_order.coupon_count
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Integer getCouponCount() {
        return couponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.coupon_count
     *
     * @param couponCount the value for t_wx_pay_order.coupon_count
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setCouponCount(Integer couponCount) {
        this.couponCount = couponCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.time_end
     *
     * @return the value of t_wx_pay_order.time_end
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Date getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.time_end
     *
     * @param timeEnd the value for t_wx_pay_order.time_end
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.out_refund_no
     *
     * @return the value of t_wx_pay_order.out_refund_no
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.out_refund_no
     *
     * @param outRefundNo the value for t_wx_pay_order.out_refund_no
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.refund_fee_type
     *
     * @return the value of t_wx_pay_order.refund_fee_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getRefundFeeType() {
        return refundFeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.refund_fee_type
     *
     * @param refundFeeType the value for t_wx_pay_order.refund_fee_type
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setRefundFeeType(String refundFeeType) {
        this.refundFeeType = refundFeeType == null ? null : refundFeeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.op_user_id
     *
     * @return the value of t_wx_pay_order.op_user_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getOpUserId() {
        return opUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.op_user_id
     *
     * @param opUserId the value for t_wx_pay_order.op_user_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setOpUserId(String opUserId) {
        this.opUserId = opUserId == null ? null : opUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.refund_id
     *
     * @return the value of t_wx_pay_order.refund_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.refund_id
     *
     * @param refundId the value for t_wx_pay_order.refund_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId == null ? null : refundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.refund_channel
     *
     * @return the value of t_wx_pay_order.refund_channel
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getRefundChannel() {
        return refundChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.refund_channel
     *
     * @param refundChannel the value for t_wx_pay_order.refund_channel
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setRefundChannel(String refundChannel) {
        this.refundChannel = refundChannel == null ? null : refundChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.cash_refund_fee
     *
     * @return the value of t_wx_pay_order.cash_refund_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Double getCashRefundFee() {
        return cashRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.cash_refund_fee
     *
     * @param cashRefundFee the value for t_wx_pay_order.cash_refund_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setCashRefundFee(Double cashRefundFee) {
        this.cashRefundFee = cashRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.coupon_refund_fee
     *
     * @return the value of t_wx_pay_order.coupon_refund_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Double getCouponRefundFee() {
        return couponRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.coupon_refund_fee
     *
     * @param couponRefundFee the value for t_wx_pay_order.coupon_refund_fee
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setCouponRefundFee(Double couponRefundFee) {
        this.couponRefundFee = couponRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.coupon_refund_count
     *
     * @return the value of t_wx_pay_order.coupon_refund_count
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public Integer getCouponRefundCount() {
        return couponRefundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.coupon_refund_count
     *
     * @param couponRefundCount the value for t_wx_pay_order.coupon_refund_count
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setCouponRefundCount(Integer couponRefundCount) {
        this.couponRefundCount = couponRefundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.coupon_refund_id
     *
     * @return the value of t_wx_pay_order.coupon_refund_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getCouponRefundId() {
        return couponRefundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.coupon_refund_id
     *
     * @param couponRefundId the value for t_wx_pay_order.coupon_refund_id
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setCouponRefundId(String couponRefundId) {
        this.couponRefundId = couponRefundId == null ? null : couponRefundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.refund_status
     *
     * @return the value of t_wx_pay_order.refund_status
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.refund_status
     *
     * @param refundStatus the value for t_wx_pay_order.refund_status
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_pay_order.refund_recv_accout
     *
     * @return the value of t_wx_pay_order.refund_recv_accout
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public String getRefundRecvAccout() {
        return refundRecvAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_pay_order.refund_recv_accout
     *
     * @param refundRecvAccout the value for t_wx_pay_order.refund_recv_accout
     *
     * @mbggenerated Thu Mar 10 15:51:20 CST 2016
     */
    public void setRefundRecvAccout(String refundRecvAccout) {
        this.refundRecvAccout = refundRecvAccout == null ? null : refundRecvAccout.trim();
    }

	public Integer getModel() {
		return model;
	}

	public void setModel(Integer model) {
		this.model = model;
	}

	public Integer getPay_type() {
		return pay_type;
	}

	public void setPay_type(Integer pay_type) {
		this.pay_type = pay_type;
	}

	public Integer getBus_id() {
		return bus_id;
	}

	public void setBus_id(Integer bus_id) {
		this.bus_id = bus_id;
	}

	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public Integer getPaySource() {
		return paySource;
	}

	public void setPaySource(Integer paySource) {
		this.paySource = paySource;
	}

	public String getSubmitNum() {
		return submitNum;
	}

	public void setSubmitNum(String submitNum) {
		this.submitNum = submitNum;
	}
}