package com.gt.mall.bean;

import java.io.Serializable;
import java.util.Date;

public class WxPublicUsers implements Serializable{
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.id
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.wx_user_token
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String wxUserToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.auth_refresh_token
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String authRefreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.bus_user_id
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer busUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.authorizer_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String authorizerInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.head_img
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.service_type_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer serviceTypeInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.verify_type_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer verifyTypeInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.user_name
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.alias
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.qrcode_url
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String qrcodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.appid
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.appsecret
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String appsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.func_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String funcInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.access_token
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.token_last_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Date tokenLastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.token_duration
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer tokenDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.apiticket
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String apiticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.api_ticket_duration
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer apiTicketDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.api_ticket_last_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Date apiTicketLastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.create_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.modify_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.total_voice_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer totalVoiceCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.total_video_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer totalVideoCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.total_image_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer totalImageCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.total_news_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer totalNewsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.use_news_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer useNewsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.use_voice_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer useVoiceCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.use_video_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer useVideoCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.use_image_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer useImageCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.is_friend_reply_open
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer isFriendReplyOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.is_autoreply_open
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer isAutoreplyOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.is_template_open
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer isTemplateOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.total_bulk
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer totalBulk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.use_bulk
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer useBulk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.mch_id
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.api_key
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private String apiKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_public_users.is_power
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    private Integer isPower;



    private String businessInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.id
     *
     * @return the value of t_wx_public_users.id
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.id
     *
     * @param id the value for t_wx_public_users.id
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.wx_user_token
     *
     * @return the value of t_wx_public_users.wx_user_token
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getWxUserToken() {
        return wxUserToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.wx_user_token
     *
     * @param wxUserToken the value for t_wx_public_users.wx_user_token
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setWxUserToken(String wxUserToken) {
        this.wxUserToken = wxUserToken == null ? null : wxUserToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.auth_refresh_token
     *
     * @return the value of t_wx_public_users.auth_refresh_token
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getAuthRefreshToken() {
        return authRefreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.auth_refresh_token
     *
     * @param authRefreshToken the value for t_wx_public_users.auth_refresh_token
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setAuthRefreshToken(String authRefreshToken) {
        this.authRefreshToken = authRefreshToken == null ? null : authRefreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.bus_user_id
     *
     * @return the value of t_wx_public_users.bus_user_id
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getBusUserId() {
        return busUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.bus_user_id
     *
     * @param busUserId the value for t_wx_public_users.bus_user_id
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setBusUserId(Integer busUserId) {
        this.busUserId = busUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.authorizer_info
     *
     * @return the value of t_wx_public_users.authorizer_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getAuthorizerInfo() {
        return authorizerInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.authorizer_info
     *
     * @param authorizerInfo the value for t_wx_public_users.authorizer_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setAuthorizerInfo(String authorizerInfo) {
        this.authorizerInfo = authorizerInfo == null ? null : authorizerInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.head_img
     *
     * @return the value of t_wx_public_users.head_img
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.head_img
     *
     * @param headImg the value for t_wx_public_users.head_img
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.service_type_info
     *
     * @return the value of t_wx_public_users.service_type_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getServiceTypeInfo() {
        return serviceTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.service_type_info
     *
     * @param serviceTypeInfo the value for t_wx_public_users.service_type_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setServiceTypeInfo(Integer serviceTypeInfo) {
        this.serviceTypeInfo = serviceTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.verify_type_info
     *
     * @return the value of t_wx_public_users.verify_type_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getVerifyTypeInfo() {
        return verifyTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.verify_type_info
     *
     * @param verifyTypeInfo the value for t_wx_public_users.verify_type_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setVerifyTypeInfo(Integer verifyTypeInfo) {
        this.verifyTypeInfo = verifyTypeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.user_name
     *
     * @return the value of t_wx_public_users.user_name
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.user_name
     *
     * @param userName the value for t_wx_public_users.user_name
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.alias
     *
     * @return the value of t_wx_public_users.alias
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.alias
     *
     * @param alias the value for t_wx_public_users.alias
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.qrcode_url
     *
     * @return the value of t_wx_public_users.qrcode_url
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.qrcode_url
     *
     * @param qrcodeUrl the value for t_wx_public_users.qrcode_url
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.appid
     *
     * @return the value of t_wx_public_users.appid
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.appid
     *
     * @param appid the value for t_wx_public_users.appid
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.appsecret
     *
     * @return the value of t_wx_public_users.appsecret
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.appsecret
     *
     * @param appsecret the value for t_wx_public_users.appsecret
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.func_info
     *
     * @return the value of t_wx_public_users.func_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getFuncInfo() {
        return funcInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.func_info
     *
     * @param funcInfo the value for t_wx_public_users.func_info
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setFuncInfo(String funcInfo) {
        this.funcInfo = funcInfo == null ? null : funcInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.access_token
     *
     * @return the value of t_wx_public_users.access_token
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.access_token
     *
     * @param accessToken the value for t_wx_public_users.access_token
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.token_last_time
     *
     * @return the value of t_wx_public_users.token_last_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Date getTokenLastTime() {
        return tokenLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.token_last_time
     *
     * @param tokenLastTime the value for t_wx_public_users.token_last_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setTokenLastTime(Date tokenLastTime) {
        this.tokenLastTime = tokenLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.token_duration
     *
     * @return the value of t_wx_public_users.token_duration
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getTokenDuration() {
        return tokenDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.token_duration
     *
     * @param tokenDuration the value for t_wx_public_users.token_duration
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setTokenDuration(Integer tokenDuration) {
        this.tokenDuration = tokenDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.apiticket
     *
     * @return the value of t_wx_public_users.apiticket
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getApiticket() {
        return apiticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.apiticket
     *
     * @param apiticket the value for t_wx_public_users.apiticket
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setApiticket(String apiticket) {
        this.apiticket = apiticket == null ? null : apiticket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.api_ticket_duration
     *
     * @return the value of t_wx_public_users.api_ticket_duration
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getApiTicketDuration() {
        return apiTicketDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.api_ticket_duration
     *
     * @param apiTicketDuration the value for t_wx_public_users.api_ticket_duration
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setApiTicketDuration(Integer apiTicketDuration) {
        this.apiTicketDuration = apiTicketDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.api_ticket_last_time
     *
     * @return the value of t_wx_public_users.api_ticket_last_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Date getApiTicketLastTime() {
        return apiTicketLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.api_ticket_last_time
     *
     * @param apiTicketLastTime the value for t_wx_public_users.api_ticket_last_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setApiTicketLastTime(Date apiTicketLastTime) {
        this.apiTicketLastTime = apiTicketLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.create_time
     *
     * @return the value of t_wx_public_users.create_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.create_time
     *
     * @param createTime the value for t_wx_public_users.create_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.modify_time
     *
     * @return the value of t_wx_public_users.modify_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.modify_time
     *
     * @param modifyTime the value for t_wx_public_users.modify_time
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.total_voice_count
     *
     * @return the value of t_wx_public_users.total_voice_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getTotalVoiceCount() {
        return totalVoiceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.total_voice_count
     *
     * @param totalVoiceCount the value for t_wx_public_users.total_voice_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setTotalVoiceCount(Integer totalVoiceCount) {
        this.totalVoiceCount = totalVoiceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.total_video_count
     *
     * @return the value of t_wx_public_users.total_video_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getTotalVideoCount() {
        return totalVideoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.total_video_count
     *
     * @param totalVideoCount the value for t_wx_public_users.total_video_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setTotalVideoCount(Integer totalVideoCount) {
        this.totalVideoCount = totalVideoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.total_image_count
     *
     * @return the value of t_wx_public_users.total_image_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getTotalImageCount() {
        return totalImageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.total_image_count
     *
     * @param totalImageCount the value for t_wx_public_users.total_image_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setTotalImageCount(Integer totalImageCount) {
        this.totalImageCount = totalImageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.total_news_count
     *
     * @return the value of t_wx_public_users.total_news_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getTotalNewsCount() {
        return totalNewsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.total_news_count
     *
     * @param totalNewsCount the value for t_wx_public_users.total_news_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setTotalNewsCount(Integer totalNewsCount) {
        this.totalNewsCount = totalNewsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.use_news_count
     *
     * @return the value of t_wx_public_users.use_news_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getUseNewsCount() {
        return useNewsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.use_news_count
     *
     * @param useNewsCount the value for t_wx_public_users.use_news_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setUseNewsCount(Integer useNewsCount) {
        this.useNewsCount = useNewsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.use_voice_count
     *
     * @return the value of t_wx_public_users.use_voice_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getUseVoiceCount() {
        return useVoiceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.use_voice_count
     *
     * @param useVoiceCount the value for t_wx_public_users.use_voice_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setUseVoiceCount(Integer useVoiceCount) {
        this.useVoiceCount = useVoiceCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.use_video_count
     *
     * @return the value of t_wx_public_users.use_video_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getUseVideoCount() {
        return useVideoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.use_video_count
     *
     * @param useVideoCount the value for t_wx_public_users.use_video_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setUseVideoCount(Integer useVideoCount) {
        this.useVideoCount = useVideoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.use_image_count
     *
     * @return the value of t_wx_public_users.use_image_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getUseImageCount() {
        return useImageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.use_image_count
     *
     * @param useImageCount the value for t_wx_public_users.use_image_count
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setUseImageCount(Integer useImageCount) {
        this.useImageCount = useImageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.is_friend_reply_open
     *
     * @return the value of t_wx_public_users.is_friend_reply_open
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getIsFriendReplyOpen() {
        return isFriendReplyOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.is_friend_reply_open
     *
     * @param isFriendReplyOpen the value for t_wx_public_users.is_friend_reply_open
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setIsFriendReplyOpen(Integer isFriendReplyOpen) {
        this.isFriendReplyOpen = isFriendReplyOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.is_autoreply_open
     *
     * @return the value of t_wx_public_users.is_autoreply_open
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getIsAutoreplyOpen() {
        return isAutoreplyOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.is_autoreply_open
     *
     * @param isAutoreplyOpen the value for t_wx_public_users.is_autoreply_open
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setIsAutoreplyOpen(Integer isAutoreplyOpen) {
        this.isAutoreplyOpen = isAutoreplyOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.is_template_open
     *
     * @return the value of t_wx_public_users.is_template_open
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getIsTemplateOpen() {
        return isTemplateOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.is_template_open
     *
     * @param isTemplateOpen the value for t_wx_public_users.is_template_open
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setIsTemplateOpen(Integer isTemplateOpen) {
        this.isTemplateOpen = isTemplateOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.total_bulk
     *
     * @return the value of t_wx_public_users.total_bulk
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getTotalBulk() {
        return totalBulk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.total_bulk
     *
     * @param totalBulk the value for t_wx_public_users.total_bulk
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setTotalBulk(Integer totalBulk) {
        this.totalBulk = totalBulk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.use_bulk
     *
     * @return the value of t_wx_public_users.use_bulk
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getUseBulk() {
        return useBulk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.use_bulk
     *
     * @param useBulk the value for t_wx_public_users.use_bulk
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setUseBulk(Integer useBulk) {
        this.useBulk = useBulk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.mch_id
     *
     * @return the value of t_wx_public_users.mch_id
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.mch_id
     *
     * @param mchId the value for t_wx_public_users.mch_id
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.api_key
     *
     * @return the value of t_wx_public_users.api_key
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.api_key
     *
     * @param apiKey the value for t_wx_public_users.api_key
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey == null ? null : apiKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_public_users.is_power
     *
     * @return the value of t_wx_public_users.is_power
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public Integer getIsPower() {
        return isPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_public_users.is_power
     *
     * @param isPower the value for t_wx_public_users.is_power
     *
     * @mbggenerated Mon Aug 17 14:50:16 CST 2015
     */
    public void setIsPower(Integer isPower) {
        this.isPower = isPower;
    }

    public String getBusinessInfo() {
        return businessInfo;
    }

    public void setBusinessInfo(String businessInfo) {
        this.businessInfo = businessInfo;
    }
}