######################## Spring Profile 切换环境 ########################
## 切换日志环境、数据源等配置
#  默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   堡垒环境：java -jar my -spring-boot.jar --spring.profiles.active=prod
#  注意 "---" 表示：一组配置
# 堡垒环境配置
spring:
# profiles: dev
 #redis配置
 redis:
  #host: 113.106.202.51
  #port: 6379
  password: gt@123456
  database: 4
  timeout: 1000
  pool:
    max-active: 50
    max-wait: -1
    max-idle: 20
    min-idle: 0
    #redis集群配置
  cluster:
    nodes: 113.106.202.51:6379,113.106.202.50:9379,113.106.202.54:9379
    max-attempts: 6
    max-redirects: 6
    #redis哨兵模式配置
  sentinel:
    nodes: 113.106.202.51:26379,113.106.202.50:29379,113.106.202.54:29379
    master: mymaster

#redis session共享
 session:
   store-type: redis
#自动重启默认开发时开启
 devtools:
  restart:
   enabled: true
 thymeleaf:
   cache: false



 datasource:
   druid:
     url: jdbc:mysql://183.47.242.2:3306/gt_mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
     username: root
     password: gt26609632
     # 下面为连接池的补充设置，应用到上面所有数据源中
     # 初始化大小，最小，最大
     initial-size: 10
     max-active: 50
     # 配置获取连接等待超时的时间
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 五分钟
     timeBetweenEvictionRunsMillis: 300000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 30000
     validationQuery: select 1
     testWhileIdle: true
     testOnBorrow: true
     testOnReturn: true
     # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     filters: stat,wall,slf4j
     # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     # 合并多个DruidDataSource的监控数据
     stat-view-servlet:
#      IP白(allow)/黑(deny)名单 (存在共同时，deny优先于allow) : 如果满足deny的话提示:Sorry, you are not permitted to view this page.
      allow: 127.0.0.1,192.168.3.47
      login-username: admin
      login-password: admin
      reset-enable: false
      url-pattern: /druid/*
      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      # 如果spring.datasource.druid.aop-patterns要代理的类没有定义interface请设置spring.aop.proxy-target-class=true
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
     aop-patterns: com.gt.mall.*.service.*,com.gt.mall.*.dao.*
     #批量新增修改
     filter:
      wall:
       config:
        multi-statement-allow: true


######################## 堡垒环境配置 ########################
# 是否开启Swagger接口展示
swagger:
  show: false
#JedisUtil 用到的配置
redis:
 host: 113.106.202.51
 port: 6381
 password: GT@123456
 database: 0

### 设置 Redis session 共享
redisSession:
 domainName: .deeptel.com.cn
 cookiePath: /
 cookieName: WXMPJSESSIONID

web:
 #域名
 domain: nb.mall.deeptel.com.cn
 #网页访问路径
 homeUrl: https://nb.mall.deeptel.com.cn/
 #手机端页面路径访问
 phoneWebHomeUrl: https://nb.mall.deeptel.com.cn/html/phone/index.html#
 #商城营销路径
 marketingUrl: https://nb.core.deeptel.com.cn/html/application/busAdded/index.html?dictstyle=05f8fd040284859d
 #素材库路径
 materialUrl: https://nb.suc.deeptel.com.cn/common/material.do
 #多粉二维码关注
 duofenTwoCodeUrl: http://maint.deeptel.com.cn/image/2/gh_32251ec4c8e9/1/1509331696065.jpg
 #多粉的公众号id（用作给商家发送消息模板）
 duofenPublicId: 482

####图片资源ftp 配置
static:
 source:
  ftp:
   #FTP Ip
   ip: 183.47.242.3
   #FTP 端口号
   port: 21
   #FTP 用户名
   user: gt123456
   #FTP 密码
   password: gt123456
#访问文章资源URL
article:
 url:
  prefix: https://nb.mall.deeptel.com.cn/
#访问资源URL
resource:
 url:
  prefix: https://maint.duofriend.com/upload/

#图片存放路径
res:
 image:
  path: /home/server/project/staticSource/upload/image

#电信流量订单前缀
dianxin:
 order: df

#消息队列
mq:
 ip: 113.106.202.51
 port: 5672
 user: guest
 password: gt@123456@
 seckill:
  #队列转换器
  exchange: mall.fort.seckill.exchange
  #队列名称
  queueName: mall.fort.seckill.queueName

http:
 #总项目请求地址
 wxmp:
  domain: https://nb.deeptel.com.cn/
  key: WXMP2017
 #会员key 和 请求地址
 member:
  domain: https://nb.member.deeptel.com.cn/
  key: MV8MMFQUMU1HJ6F2GNH40ZFJJ7Q8LNVM
 #联盟 key  和请求地址
 union:
  domain: https://nb.union.deeptel.com.cn/
  key: SR36E9KIYDLIU1VB6WX20HCW494QL97T
 #进销存的请求地址、token 用户名  和token密码
 jxc:
  #进销存 地址
  domain: http://jxc.duofee.com/jxc/
  #进销存token用户名
  account: e_shop
  #进销存token密码
  pwx: shop12345
 core:
  # 增值服务域名
  domain: https://nb.core.deeptel.com.cn/
  #增值服务 key
  key: APPLIC2017
 #硬件
 hardware:
  #硬件地址
  domain: https://nb.yj.deeptel.com.cn/
 #钱包支付
 dfPay:
  #钱包支付域名
  domain: https://nb.dfpay.deeptel.com.cn/
  #钱包支付 key
  key: WALLET2017
