######################## Spring Profile 切换环境 ########################
## 切换日志环境、数据源等配置
#  默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my -spring-boot.jar --spring.profiles.active=prod
#  注意 "---" 表示：一组配置
# 测试环境配置
spring:
  redis:
     host: 14.29.79.226
     port: 6379
     password: gt@123456
   session:
     store-type: redis
 #redis配置
  redis:
    host: 14.29.79.226
    port: 6379
    password: gt@123456
 session:
   store-type: redis
# profiles: test
datasource:
 druid:
  url: jdbc:mysql://114.29.79.226:3306/gt_mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
  username: zhangmz
  password: zhangmz123
  driver-class-name: com.mysql.jdbc.Driver
  platform: mysql
  type: com.alibaba.druid.pool.DruidDataSource
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 5
  minIdle: 10
  maxActive: 100
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall,slf4j
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个DruidDataSource的监控数据
  #useGlobalDataSourceStat: true
server:
  port: 8081
  session:
    timeout: 30

######################## 开发环境配置 ########################
web:
 #主域名
 wxmp:
  domain: http://sz.yifriend.net
 #域名
 domain: 192.168.2.100:8081
 #网页访问路径
 homeUrl: http://192.168.2.100:8081/
 #进销存 地址
 jxcUrl: http://jxc.duofee.com/jxc/
 #进销存token用户名
 jxcAccount: e_shop
 #进销存token密码
 jxcPwd: shop12345


####图片资源ftp 配置
static:
 source:
  ftp:
   #FTP Ip
   ip: 120.25.154.127
   #FTP 端口号
   port: 21
   #FTP 用户名
   user: gt123456
   #FTP 密码
   password: gt12345612
#访问文章资源URL
article:
 url:
  prefix: http://192.168.2.100:8081/
#访问资源URL
resource:
 url:
  prefix: http://maint.yifriend.net/upload/

#图片存放路径
res:
 image:
  path: D:/apache-tomcat-7.0.59/wtpwebapps/wxmp/upload/image

#电信流量订单前缀
dianxin:
 order: df

#消息队列
mq:
 #队列转换器
 exchange: gt.exchange.message
 #队列名称
 queueName: gt.queueName.message